Models/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Paper(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    abstract = db.Column(db.Text, nullable=True)
    keywords = db.Column(db.String(100), nullable=True)
    file = db.Column(db.LargeBinary, nullable=False)  # Store PDF data as binary
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    reviewer_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    grade = db.Column(db.Integer, nullable=True)
    feedback = db.Column(db.Text, nullable=True)

    author = db.relationship('User', foreign_keys=[author_id],
                                  backref=db.backref('submitted_papers', lazy=True))
    reviewer = db.relationship('User', foreign_keys=[reviewer_id],
                                    backref=db.backref('reviewed_papers', lazy=True))

    def __init__(self, title, abstract, keywords, file, author_id, reviewer_id, grade, feedback):
        self.title = title
        self.abstract = abstract
        self.keywords = keywords
        self.file = file
        self.author_id = author_id
        self.reviewer_id = reviewer_id
        self.grade = grade
        self.feedback = feedback


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    email = db.Column(db.String(100), unique=True)
    password_hash = db.Column(db.String(128))
    role = db.Column(db.String(50))  # Role of the user (e.g., 'author' or 'reviewer')

    def __init__(self, name, email, password, role):
        self.name = name
        self.email = email
        self.set_password(password)
        self.role = role

    def set_password(self, password):
        self.password_hash = password

    def check_password(self, password):
        return self.password_hash == password

Controllers/controllers.py
from flask import Blueprint, request, redirect, url_for, flash, render_template, session

from Services.services import check_session, login_user, register_user, submit_paper, get_submitted_papers, \
    get_assigned_papers, get_paper_by_id, review_paper, download_pdf_for_reviewer, get_all_users, get_all_papers

bp = Blueprint('controllers', __name__)


@bp.route('/')
def home_page():
    user_id, user_role, user_name = check_session()

    return render_template('index.html', user_id=user_id, user_name=user_name, user_role=user_role)


@bp.route('/conferences')
def conference_page():
    user_id, user_role, user_name = check_session()

    return render_template('conferences.html', user_id=user_id, user_name=user_name, user_role=user_role)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    user_id, _, _ = check_session()
    status = None
    if user_id:  # Redirect to home page if user is already logged in
        return redirect(url_for('controllers.home_page'))

    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        status = login_user(email, password)
    if status == "success":
        return redirect(url_for('controllers.home_page'))

    return render_template('login.html')


@bp.route('/register', methods=['GET', 'POST'])
def register():
    user_id, _, _ = check_session()
    status = None
    if user_id:  # Redirect to home page if user is already logged in
        return redirect(url_for('controllers.home_page'))

    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        password = request.form['password']
        confirm_password = request.form['confirm_password']
        role = request.form['role']

        status = register_user(name, email, password, confirm_password, role)
    if status == "success":
        return redirect(url_for('controllers.login'))

    return render_template('register.html')


@bp.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect(url_for('controllers.home_page'))


@bp.route('/author/dashboard', methods=['GET', 'POST'])
def author_dashboard():
    user_id, user_role, user_name = check_session()
    if user_role != 'author':  # Redirect to home page if user is not an author
        return redirect(url_for('controllers.home_page'))

    if request.method == 'POST':
        title = request.form['paper_title']
        abstract = request.form['paper_abstract']
        keywords = request.form['paper_keywords']
        is_pdf = request.files['paper_file'].filename.endswith('.pdf')
        file = request.files['paper_file'].read()
        author_id = session['user_id']

        submit_paper(title, abstract, keywords, is_pdf, file, author_id)

    submitted_papers = get_submitted_papers(user_id)

    return render_template('author_dashboard.html', user_name=user_name, submitted_papers=submitted_papers)


@bp.route('/reviewer/dashboard')
def reviewer_dashboard():
    user_id, user_role, user_name = check_session()
    if user_role != 'reviewer':  # Redirect to home page if user is not a reviewer
        return redirect(url_for('controllers.home_page'))

    assigned_papers = get_assigned_papers(user_id)

    return render_template('reviewer_dashboard.html', user_name=user_name, assigned_papers=assigned_papers)


@bp.route('/download_pdf/<int:paper_id>')
def download_pdf(paper_id):
    user_id, user_role, _ = check_session()
    if user_role != 'reviewer':  # Redirect to home page if user is not a reviewer
        return redirect(url_for('controllers.home_page'))

    assigned_papers = get_assigned_papers(user_id)

    if paper_id not in [paper.id for paper in assigned_papers]:  # Redirect to reviewer dashboard if paper is not
        # assigned to reviewer
        flash('You are not assigned to review this paper.')
        return redirect(url_for('controllers.reviewer_dashboard'))

    return download_pdf_for_reviewer(paper_id)


@bp.route('/feedback/<int:paper_id>', methods=['GET', 'POST'])
def feedback_popup(paper_id):
    _, user_role, _ = check_session()
    if user_role != 'reviewer':  # Redirect to home page if user is not a reviewer
        return redirect(url_for('controllers.home_page'))

    paper = get_paper_by_id(paper_id)
    if request.method == 'POST':
        grade = request.form.get('grade')
        feedback = request.form.get('feedback')

        review_paper(paper_id, grade, feedback)

    return render_template('feedback_popup.html', paper_id=paper.id, grade=paper.grade, feedback=paper.feedback)


@bp.route('/set_up_conference')
def conference_setup():
    user_id, user_role, user_name = check_session()
    if user_role != 'organizer':  # Redirect to home page if user is not an organizer
        return redirect(url_for('controllers.home_page'))

    return render_template('conference_setup.html', user_name=user_name, user_id=user_id, user_role=user_role)


@bp.route('/qr_attendee')
def qr_attendee():
    user_id, user_role, user_name = check_session()
    if user_role != 'attendee':
        return redirect(url_for('controllers.home_page'))

    return render_template('qr_attendee.html', user_name=user_name, user_id=user_id, user_role=user_role)


@bp.route('/review_conference')
def conference_review():
    user_id, user_role, user_name = check_session()
    if user_role != 'attendee':
        return redirect(url_for('controllers.home_page'))

    return render_template('conference_review.html', user_name=user_name, user_id=user_id, user_role=user_role)


@bp.route('/conference_register')
def conference_register():
    user_id, user_role, user_name = check_session()
    if user_role != 'attendee':
        return redirect(url_for('controllers.home_page'))

    return render_template('conference_register.html', user_name=user_name, user_id=user_id, user_role=user_role)


@bp.route('/admin')
def admin():
    users = get_all_users()
    papers = get_all_papers()

    return render_template('admin.html', users=users, papers=papers)

app.py
from flask import Flask
from Controllers.controllers import bp as controllers_bp
from Models.models import db

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
app.config['SECRET_KEY'] = 'your_secret_key_here'

app.register_blueprint(controllers_bp)

db.init_app(app)


with app.app_context():
    db.create_all()

if __name__ == '__main__':
    app.run()

templates/author_dashboard.html
{% extends 'base.html' %}
{% block head %}
    <title>Author Dashboard</title>
{% endblock %}
{% block body %}
    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close">
                <span class="icofont-close js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>

    <nav class="site-nav">
        <div class="container">
            <div class="menu-bg-wrap">
                <div class="site-navigation">
                    <a href="{{ url_for('controllers.home_page') }}" class="logo m-0 float-start">CMS</a>

                    <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
                        {% if user_name is not none %}
                            <li class="active" style="color: white"><a>Welcome, {{ user_name }}</a></li>
                        {% endif %}
                        <li><a href="{{ url_for('controllers.home_page') }}">Home</a></li>
                        <li><a href="{{ url_for('controllers.conference_page') }}">Conferences</a></li>
                        <li class="active"><a href="{{ url_for('controllers.author_dashboard') }}">Dashboard</a></li>
                        <li><a href="{{ url_for('controllers.logout') }}">Logout</a></li>
                    </ul>

                    <a href="#"
                       class="burger light me-auto float-end mt-1 site-menu-toggle js-menu-toggle d-inline-block d-lg-none"
                       data-toggle="collapse" data-target="#main-navbar">
                        <span></span>
                    </a>
                </div>
            </div>
        </div>
    </nav>


    <div
            class="hero page-inner overlay"
            style="background-image: url('{{ url_for('static', filename='images/hero_bg_3.jpg') }}'); height: fit-content"
    >
        <div class="container">
            <div class="row justify-content-center align-items-center" style="height: fit-content;">
                <div class="col-lg-9 text-center mt-5">
                    <h1 class="heading" data-aos="fade-up">Author Dashboard</h1>

                    <nav
                            aria-label="breadcrumb"
                            data-aos="fade-up"
                            data-aos-delay="200"
                    >
                        <ol class="breadcrumb text-center justify-content-center">
                            <li class="breadcrumb-item"><a href="{{ url_for('controllers.home_page') }}">Home</a></li>
                            <li
                                    class="breadcrumb-item active text-white-50"
                                    aria-current="page"
                            >
                                Author Dashboard
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>


    <div class="container mt-5">
        <h1>Welcome to the Author Dashboard</h1>
        <form method="post" action="{{ url_for('controllers.author_dashboard') }}" enctype="multipart/form-data">
            <div class="form-group">
                <label for="paper_title">Paper Title:</label>
                <input type="text" class="form-control" id="paper_title" name="paper_title" maxlength="30" required>
            </div>
            <div class="form-group">
                <label for="paper_abstract">Paper Abstract:</label>
                <textarea class="form-control" id="paper_abstract" name="paper_abstract" rows="4" maxlength="200"
                          required></textarea>
            </div>
            <div class="form-group">
                <label for="paper_keywords">Paper Keywords:</label>
                <input type="text" class="form-control" id="paper_keywords" name="paper_keywords" maxlength="30"
                       required>
            </div>
            <div class="form-group mt-3">
                <label for="paper_file">Upload Paper (PDF):</label>
                <input type="file" class="form-control-file" id="paper_file" name="paper_file" required>
            </div>
            <button type="submit" class="btn btn-primary mt-3 mb-10">Submit Paper</button>
        </form>
    </div>

    <div class="container">
        <br>
        <h2>Submitted Papers</h2>
        <ul class="list-group">
            {%if assigned_papers|length == 0%}
                <h4>No papers submitted yet!</h4>
            {% endif %}
            {% for paper in submitted_papers %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h5>{{ paper.title }}</h5>
                            <p> Grade: {{ paper.grade }}</p>
                            <p> Feedback: {{ paper.feedback }}</p>
                            <p> Abstract: {{ paper.abstract[:50] }}{% if paper.abstract|length > 50 %}...{% endif %}</p>
                            <p> Keywords: {{ paper.keywords }}</p>
                            {% if paper.grade is none %}
                                <p style="color: #6610f2"> Status: Pending</p>
                            {% elif paper.grade < 5 %}
                                <p style="color: red"> Status: Rejected</p>
                            {% else %}
                                <p style="color: green"> Status: Accepted</p>
                            {% endif %}
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <br>
            <br>
            <br>
            <br>
            <div class="container">
                {% for message in messages %}
                    {% if message.strip() == 'Paper uploaded successfully.' %}
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                    {% else %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
{% endblock %}

templates/conference_register.html
{% extends 'base.html' %}
{% block head %}
    <title>QR Attendee</title>
{% endblock %}
{% block body %}
    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close">
                <span class="icofont-close js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>

    <nav class="site-nav">
        <div class="container">
            <div class="menu-bg-wrap">
                <div class="site-navigation">
                    <a href="{{ url_for('controllers.home_page') }}" class="logo m-0 float-start">CMS</a>

                    <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
                        {% if user_name is not none %}
                            <li class="active" style="color: white"><a>Welcome, {{ user_name }}</a></li>
                        {% endif %}
                        <li><a href="{{ url_for('controllers.home_page') }}">Home</a></li>
                        <li><a href="{{ url_for('controllers.conference_page') }}">Conferences</a></li>
                        <li><a href="{{ url_for('controllers.qr_attendee') }}">QR</a></li>
                        <li><a href="{{ url_for('controllers.conference_review') }}">Review Past Conferences</a></li>
                        <li><a href="{{ url_for('controllers.logout') }}">Logout</a></li>
                    </ul>

                    <a href="#"
                       class="burger light me-auto float-end mt-1 site-menu-toggle js-menu-toggle d-inline-block d-lg-none"
                       data-toggle="collapse" data-target="#main-navbar">
                        <span></span>
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <div class="section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 mt-5" data-aos="fade-up" data-aos-delay="200">
                    <form method="post">
                        <div class="mb-3">
                            <label for="card_number" class="form-label">Credit Card Number</label>
                            <input type="text" name="card_number" id="card_number" class="form-control" placeholder="Enter card number" required>
                        </div>
                        <div class="mb-3">
                            <label for="expiry_date" class="form-label">Expiry Date</label>
                            <input type="text" name="expiry_date" id="expiry_date" class="form-control" placeholder="MM/YYYY" required>
                        </div>
                        <div class="mb-3">
                            <label for="cvv" class="form-label">CVV</label>
                            <input type="text" name="cvv" id="cvv" class="form-control" placeholder="Enter CVV" required>
                        </div>
                        <div class="mb-3">
                            <label for="name_on_card" class="form-label">Name on Card</label>
                            <input type="text" name="name_on_card" id="name_on_card" class="form-control" placeholder="Enter name on card" required>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="form-label">Amount ($)</label>
                            <input type="text" name="amount" id="amount" class="form-control" value="30" readonly>
                        </div>
                        <input type="submit" value="Make Payment" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/conference_review.html
{% extends 'base.html' %}
{% block head %}
    <title>QR Attendee</title>
{% endblock %}
{% block body %}
    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close">
                <span class="icofont-close js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>

    <nav class="site-nav">
        <div class="container">
            <div class="menu-bg-wrap">
                <div class="site-navigation">
                    <a href="{{ url_for('controllers.home_page') }}" class="logo m-0 float-start">CMS</a>

                    <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
                        {% if user_name is not none %}
                            <li class="active" style="color: white"><a>Welcome, {{ user_name }}</a></li>
                        {% endif %}
                        <li><a href="{{ url_for('controllers.home_page') }}">Home</a></li>
                        <li><a href="{{ url_for('controllers.conference_page') }}">Conferences</a></li>
                        <li><a href="{{ url_for('controllers.qr_attendee') }}">QR</a></li>
                        <li class="active"><a href="{{ url_for('controllers.conference_review') }}">Review Past
                            Conferences</a></li>
                        <li><a href="{{ url_for('controllers.logout') }}">Logout</a></li>
                    </ul>

                    <a href="#"
                       class="burger light me-auto float-end mt-1 site-menu-toggle js-menu-toggle d-inline-block d-lg-none"
                       data-toggle="collapse" data-target="#main-navbar">
                        <span></span>
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <div
            class="hero page-inner overlay"
            style="background-image: url('{{ url_for('static', filename='images/hero_bg_3.jpg') }}'); height: fit-content"
    >
        <div class="container">
            <div class="row justify-content-center align-items-center" style="height: fit-content;">
                <div class="col-lg-9 text-center mt-5">
                    <h1 class="heading" data-aos="fade-up">Review Past Conferences!</h1>

                    <nav
                            aria-label="breadcrumb"
                            data-aos="fade-up"
                            data-aos-delay="200"
                    >
                        <ol class="breadcrumb text-center justify-content-center">
                            <li class="breadcrumb-item"><a href="{{ url_for('controllers.home_page') }}">Home</a></li>
                            <li
                                    class="breadcrumb-item active text-white-50"
                                    aria-current="page"
                            >
                                Review Past Conferences
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8" data-aos="fade-up" data-aos-delay="200">
                    <h2 class="text-center mb-4">Review Past Conferences</h2>
                    <div class="conference-list">
                        <div class="conference-item">
                            <h3>Conference Title 1</h3>
                            <p>Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            <p>Venue: Lorem Ipsum Conference Center</p>
                            <p>Dates: January 1-3, 2023</p>
                            <!-- Add more conference details as needed -->
                            <button class="btn btn-primary"><i class="icon-edit"></i>Review</button>
                        </div>
                        <br>
                        <div class="conference-item">
                            <h3>Conference Title 2</h3>
                            <p>Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            <p>Venue: Lorem Ipsum Conference Center</p>
                            <p>Dates: February 15-17, 2023</p>
                            <!-- Add more conference details as needed -->
                            <button class="btn btn-primary"><i class="icon-edit"></i>Review</button>
                        </div>
                        <!-- Add more conference items as needed -->
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/qr_attendee.html
{% extends 'base.html' %}
{% block head %}
    <title>QR Attendee</title>
{% endblock %}
{% block body %}
    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close">
                <span class="icofont-close js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>

    <nav class="site-nav">
        <div class="container">
            <div class="menu-bg-wrap">
                <div class="site-navigation">
                    <a href="{{ url_for('controllers.home_page') }}" class="logo m-0 float-start">CMS</a>

                    <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
                        {% if user_name is not none %}
                            <li class="active" style="color: white"><a>Welcome, {{ user_name }}</a></li>
                        {% endif %}
                        <li><a href="{{ url_for('controllers.home_page') }}">Home</a></li>
                        <li><a href="{{ url_for('controllers.conference_page') }}">Conferences</a></li>
                        <li class="active"><a href="{{ url_for('controllers.qr_attendee') }}">QR</a></li>
                        <li><a href="{{ url_for('controllers.conference_review') }}">Review Past Conferences</a></li>
                        <li><a href="{{ url_for('controllers.logout') }}">Logout</a></li>
                    </ul>

                    <a href="#"
                       class="burger light me-auto float-end mt-1 site-menu-toggle js-menu-toggle d-inline-block d-lg-none"
                       data-toggle="collapse" data-target="#main-navbar">
                        <span></span>
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4 mt-5">
                <div class="card mt-5">
                    <div class="card-header">{{ "QR Code Scanner" }}</div>

                    <div class="card-body">
                        <div style="border: 2px solid #000; display: flex; padding: 10px; justify-content: center; align-items: center; text-align: center; ">

                            <img src="static/images/qr-image.jpg" class="img-fluid" alt="QR Code Scanner" style="height: fit-content">
                        </div>
                        <i class="icon-camera" style="font-size: 50px; display: flex; padding: 10px; justify-content: center; align-items: center; text-align: center;"></i>
                        <p class="text-center">Click to open the QR code scanner.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reviewer_dashboard.html
{% extends 'base.html' %}
{% block head %}
    <title>Reviewer Dashboard</title>
{% endblock %}
{% block body %}
    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close">
                <span class="icofont-close js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>

    <nav class="site-nav">
        <div class="container">
            <div class="menu-bg-wrap">
                <div class="site-navigation">
                    <a href="{{ url_for('controllers.home_page') }}" class="logo m-0 float-start">CMS</a>

                    <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
                        <li class="active" style="color: white"><a>Welcome, {{ user_name }}</a></li>
                        <li><a href="{{ url_for('controllers.home_page') }}">Home</a></li>
                        <li><a href="{{ url_for('controllers.conference_page') }}">Conferences</a></li>
                        <li class="active"><a href="{{ url_for('controllers.reviewer_dashboard') }}">Dashboard</a></li>
                        <li><a href="{{ url_for('controllers.logout') }}">Logout</a></li>
                    </ul>

                    <a href="#"
                       class="burger light me-auto float-end mt-1 site-menu-toggle js-menu-toggle d-inline-block d-lg-none"
                       data-toggle="collapse" data-target="#main-navbar">
                        <span></span>
                    </a>
                </div>
            </div>
        </div>
    </nav>


    <div
            class="hero page-inner overlay"
            style="background-image: url('{{ url_for('static', filename='images/hero_bg_3.jpg') }}'); height: fit-content"
    >
        <div class="container">
            <div class="row justify-content-center align-items-center" style="height: fit-content;">
                <div class="col-lg-9 text-center mt-5">
                    <h1 class="heading mt-10" data-aos="fade-up">Reviewer Dashboard</h1>

                    <nav
                            aria-label="breadcrumb"
                            data-aos="fade-up"
                            data-aos-delay="200"
                    >
                        <ol class="breadcrumb text-center justify-content-center">
                            <li class="breadcrumb-item"><a href="{{ url_for('controllers.home_page') }}">Home</a></li>
                            <li
                                    class="breadcrumb-item active text-white-50"
                                    aria-current="page"
                            >
                                Reviewer Dashboard
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <br>
        <h1>Welcome to the Reviewer Dashboard!</h1>
        <h2>Assigned Papers</h2>
        <ul class="list-group">
            {%if assigned_papers|length == 0%}
                <h4>No papers assigned yet!</h4>
            {%endif%}
            {% for paper in assigned_papers %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h5>{{ paper.title }}</h5>
                            <p> Grade: {{ paper.grade }}</p>
                            <p> Feedback: {{ paper.feedback }}</p>
                            <p> Abstract: {{ paper.abstract[:50] }}{% if paper.abstract|length > 50 %}...{% endif %}</p>
                            <p> Keywords: {{ paper.keywords }}</p>
                            {% if paper.grade is none %}
                                <p style="color: #6610f2"> Status: Pending</p>
                            {% elif paper.grade < 5 %}
                                <p style="color: red"> Status: Rejected</p>
                            {% else %}
                                <p style="color: green"> Status: Accepted</p>
                            {% endif %}
                        </div>
                        <div class="d-flex">
                            <form method="get" action="{{ url_for('controllers.download_pdf', paper_id=paper.id) }}">

                                <button type="submit" class="mr-2 btn btn-primary"><i class="icon-download"></i>
                                    Download
                                </button>
                            </form>
                            <a href="{{ url_for('controllers.feedback_popup', paper_id=paper.id) }}" target="_blank"

                               class="btn btn-success"><i class="icon-edit"> Feedback</i>
                            </a>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
{% endblock %}